#!/bin/sh

#Check for bigneon_db
if ! grep --quiet "^\s*bigneon_db = { git=\"https://github.com/big-neon/bn-db.git\"}$" Cargo.toml ;
then
	echo "Invalid bigneon_db in Cargo.toml"
	grep "^\s*bigneon_db" Cargo.toml
	echo "To bypass this warning use: git commit --no-verify"
	exit 1
fi
exit 0
