[package]
name = "branch_rs"
version = "0.1.0"
authors = ["Mike Berry <mikethetike@tari.com>"]

[dependencies]


reqwest = "0.9"

log = "0.4"
logging = {path="../logging"}
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

derive-error="0.0.4"
