[workspace]

members = [
    "api",
    "branch_rs",
    "db",
    "facebook",
    "globee",
    "http",
    "tari-client",
    "stripe",
    "logging",
    "macros",
    "customer_io",
    "cache"
]
