ALTER TABLE holds DROP CONSTRAINT redemption_code_unique_per_event;
ALTER TABLE codes DROP CONSTRAINT redemption_code_unique_per_event;
ALTER TABLE comps DROP CONSTRAINT redemption_code_unique_per_event;
DROP FUNCTION redemption_code_unique_per_event;
